image: prusa/oe

stages:
  - build
  - deploy
  - sign

variables:
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$DEV_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - cat ~/.ssh/known_hosts
  - mkdir -p build/conf && touch build/conf/auto.conf
  - cat build/conf/auto.conf
  - echo "$DEV_CA_CERT" > sources/meta-prusa/files/dev-ca.pem
  - echo "$DEV_CA_CERT" > sources/meta-prusa/recipes-core/rauc/files/ca.cert.pem
  - echo "$DEV_CA_KEY" > sources/meta-prusa/recipes-core/rauc/files/ca.key.pem
  - echo "$DEV_CERT" > sources/meta-prusa/files/ca.cert.pem
  - echo "$DEV_KEY" > sources/meta-prusa/files/ca.key.pem
  - export VERSION=$(./version.sh)
  - echo "Version ${VERSION}"
  - export BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE} CI_COMMIT_REF_NAME CI_COMMIT_TAG"

cache:
  key: build-cache-zeus
  paths:
    - build/cache
    - build/sstate-cache
 
build:raucb:
  stage: build

  only: 
    - tags
    - merge_requests
    - web

  script:
    - cat build/conf/auto.conf
    - source oe-init-build-env
    - bitbake sla-update-bundle
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ${VERSION}.raucb
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.etc.ext4 ${VERSION}.etc.ext4
    - mv build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest ${VERSION}.initramfs.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest ${VERSION}.manifest
    - mv changelog.md ${VERSION}.changelog.md
    - mv known-issues.txt ${VERSION}.known-issues.txt

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.raucb
      - ./*.etc.ext4
      - ./*.manifest
      - ./*.changelog.md
      - ./*.known-issues.txt

build:tools:
  stage: build
  when: manual

  dependencies: []    

  only:
    - tags
    - merge_requests
    - web

  script:
    - source oe-init-build-env
    - bitbake sla-dev-image sla-bootstrap
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.wic.xz ${VERSION}.devsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.wic.bmap ${VERSION}.devsd.bmap
    - mv build/tmp/deploy/images/prusa64-sl1/sla-dev-image-prusa64-sl1-*.manifest ${VERSION}.devsd.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.xz ${VERSION}.bootstrapsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.bmap ${VERSION}.bootstrapsd.bmap

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.devsd.*
      - ./*.bootstrapsd.*

deploy:raucb:
  stage: deploy
  when: manual
  cache: {}
  
  dependencies:
    - build:raucb

  only:
    - tags
    - merge_requests
    - web

  script:
    - >
        lftp -c "
        set sftp:ssl-force yes;
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEST} ${VERSION}.raucb;
        put -O ${DEST} ${VERSION}.changelog.md;
        put -O ${DEST} ${VERSION}.known-issues.txt;
        "
    - echo "put ${VERSION}.raucb" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.changelog.md" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.known-issues.txt" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}

deploy:tools:
  stage: deploy
  when: manual
  cache: {}

  dependencies:
    - build:tools

  only:
    - tags
    - merge_requests
    - web

  script:
    - echo "put ${VERSION}.devsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.devsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.bootstrapsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${VERSION}.bootstrapsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}

sign:raub:
  stage: sign
  when: manual
  
  dependencies:
    - build:raucb

  only:
    refs:
      - tags
      - merge_requests
      - web

    variables:
      - $RAUC_CERT_FILE
      - $RAUC_KEY_FILE
      - $RAUC_KEYRING_FILE
      - $RAUC_INTERMEDIATE_FILE
      - $RAUC_PKCS11_PIN
      - $PKCS11_PROXY_SOCKET
      - $RAUC_PKCS11_MODULE

  script:
    - RAUC_KEYRING_FILE=$(echo ${RAUC_KEYRING_FILE} | sed 's/\\//g')
    - p11tool --provider ${RAUC_PKCS11_MODULE} --export ${RAUC_KEYRING_FILE} > sources/meta-prusa/recipes-core/rauc/files/ca.cert.pem
    - source oe-init-build-env
    - export BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE RAUC_CERT_FILE RAUC_KEY_FILE RAUC_INTERMEDIATE_FILE RAUC_PKCS11_PIN PKCS11_PROXY_SOCKET RAUC_PKCS11_MODULE"
    - bitbake sla-update-bundle
    - cd ..
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ${VERSION}.raucb
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.etc.ext4 ${VERSION}.etc.ext4
    - mv build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest ${VERSION}.initramfs.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest ${VERSION}.manifest
    - mv changelog.md ${VERSION}.changelog.md
    - mv known-issues.txt ${VERSION}.known-issues.txt

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.raucb
      - ./*.etc.ext4
      - ./*.manifest
      - ./*.changelog.md
      - ./*.known-issues.txt
